Repository miraikeitai2020/michisirube_camp_backend, pull requests merged in 2020-09, with the labels that each got.

#1 Setup repository
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  Makefile
  bff/Dockerfile
  bff/go.mod
  bff/go.sum
  bff/gqlgen.yml
  bff/michishirube.graphql
  bff/pkg/server/controller/controller.go
  bff/pkg/server/resolver/michishirube.go
  bff/pkg/server/resolver/resolver.go
  bff/pkg/server/server.go
  docker-compose.yml
  evaluation/Dockerfile
  evaluation/go.mod
  evaluation/go.sum
  evaluation/pkg/server/controller/controller.go
  evaluation/pkg/server/model/model.go
  evaluation/pkg/server/server.go
  recommend/Dockerfile
  recommend/go.mod
  recommend/go.sum
  recommend/pkg/server/controller/controller.go
  recommend/pkg/server/model/model.go
  recommend/pkg/server/server.go
  sample/city_query.graphql
  sample/evaluat_query.graphql
Labels: enhancement, good first issue

#5 Renwork
  LICENSE
  evaluation/pkg/server/model/model.go
Labels: good first issue

#8 Setup db
  Makefile
  db/my.cnf
  db/sql/init.sql
  docker-compose.yml
Labels: enhancement, good first issue

#9 Update init db sql
  db/sql/init.sql
Labels: enhancement
